    # plt.subplot(1, 3, 2)
    # plt.plot(G, color='green')
    # plt.title('culoare verde')
    # plt.xlabel('Abscisa')
    # plt.ylabel('Ordonata')
    
    # plt.subplot(1, 3, 3)
    # plt.plot(R, color='red')
    # plt.title('culoarea rosie')
    # plt.xlabel('Abscisa')
    # plt.ylabel('Ordonata')